### ISSUE TITLE
Allow multiple filetypes in filter option

### ISSUE THREAD

**Issue by dgdsp** [storypioneers/kirby-selector#18]

**Comment by JonasDoebertin** [comment]
The **types** option actually allows multiple file types to be specified.

Is that what you want?

**Comment by dgdsp** [comment]
thanks for the quick reply!

I would like to limit the filetypes to web-native image files.

kirby includes .psd, .tiff etc. in the type images, there fore the types option doesnt help.

if I utilise the filter option I can only define one filetype, cant I?

perfect would be sth like:

filter:
- .jpg
- .png
- .gif
- .svg

(:

**Comment by JonasDoebertin** [comment]
I think allowing multiple filters is not an optimal way to go. Users might get confused whether the filters are combine with an **AND** or an **OR** logic.

---

As a quick fix you could go ahead and change the file type associations within the toolkit code.

``` php
static public $types = array(
    'image' => array(
      'jpeg',
      'jpg',
      'jpe',
      'gif',
      'png',
      'svg',
      'ico',
      'tif',
      'tiff',
      'bmp',
      'psd',
      'ai',
      'eps',
      'ps'
    ),
    [...]
);
```

[kirby/toolkit/lib/f.php lines 121-136](https://github.com/getkirby/toolkit/blob/master/lib/f.php#L121-L136)

---

As a more permanent fix I guess the best option would be to allow regular expressions for the filter value. This would allow specify multiple and more complex filters, too. I have to research if you can put fully featured regular expressions in YAML files, though.

**Comment by JonasDoebertin** [comment]
I just implemented this. It is available in the develop branch. Have a look at [the documentation](https://github.com/storypioneers/kirby-selector/tree/develop#filter). You can use this regular expression for the filter option: `/\.((png)|(jpe?g)|(gif)|(svg))/i`. It should do the trick.

@dgdsp Maybe you can give this a quick spin and tell me if it's working for you so I can merge it into the stable release.

**Comment by JonasDoebertin** [comment]
I'm going to merge this into stable now.

**Comment by dgdsp** [comment]
Fantastic, thank you!
