### ISSUE TITLE
Use in structure

### ISSUE THREAD

**Issue by alexcarrega** [storypioneers/kirby-selector#23]
Is it possibile to use this field in structure field?

Thanks

**Comment by lauriiii** [comment]
I asked about the same thing just few hours ago: https://twitter.com/dieserjonas/status/629650985410035712

Thanks for opening the issue :)

**Comment by janstieler** [comment]
Hi,
I used it in a normal Kirby structure field. It works.
But I have a little problem to get the imageurl in it.
https://github.com/storypioneers/kirby-selector/issues/24

**Comment by JonasDoebertin** [comment]
Thanks for letting us know @janstieler!
