### ISSUE TITLE
Issue with protected variable on php 5.3.3.

### ISSUE THREAD

**Issue by iksi** [storypioneers/kirby-selector#25]
Had a problem using the kirby-selector on php 5.3.3. with line 335-338 in `selector.php`:

``` PHP
$files = $files->sortBy($this->sort, ($this->flip) ? 'desc' : 'asc')
    ->filter(function($file) use($field) {
        return $field->includeAllFiles() or in_array($file->type(), $field->types);
    });
```

Setting the `$types` variable in `selector.php` on line 70 from protected to public solves the problem and prevents kirby-selector from crashing the panel. Haven’t looked into it further yet but there must be a more elegant way to solve it.

**Comment by iksi** [comment]
One way to access it (instead of making the variable public) could be the simple addition of a public types function:

``` PHP
public function types()
{
    return $this->types;
}
```

And then calling the filter like:

``` PHP
$files = $files->sortBy($this->sort, ($this->flip) ? 'desc' : 'asc')
    ->filter(function($file) use($field) {
        return $field->includeAllFiles() or in_array($file->type(), $field->types());
    });
```

**Comment by JonasDoebertin** [comment]
~~Could you post the full error message you're getting? I can't seem to reproduce the error in PHP 5.3.29. It works just fine with this version.~~

I am indeed able to reproduce it…
