### ISSUE TITLE
Issue with large files

### ISSUE THREAD

**Issue by DavidUnzue** [storypioneers/kirby-selector#32]
After uploading a big image (3.5 MB), and using the autoselect option, the selector field and everything located under it disappear, including the save button. The problem persists until I delete the image.

**Comment by JonasDoebertin** [comment]
Could you enable the debug setting in your sites config file and have a look if you get any error message?

Seems like Kirby somehow isn't able to create the required 48x48 thumbnail file the selector uses.

You could also try with another image of similar (file-) size and have a look if it fails, too. If it doesn't maybe the image file is broken.

**Comment by DavidUnzue** [comment]
The image is definitely not corrupted, I tested it with many different images and it always happened.

With the debug option set to true, I get a "Fatal error: :  Out of memory (allocated 65011712) (tried to allocate 18432 bytes) in (...)kirby/toolkit/vendors/abeautifulsite/SimpleImage.php on line 1107", so as you already said, it seems to be a problem with the service used by Kirby to create the thumb image.

I also noticed that this is working correctly on my local environment with MAMP, but the issue arises on the server.

**Comment by JonasDoebertin** [comment]
With this info all I can tell you is that this is not an issue with the selector itself, but with your server limiting the memory that PHP is allowed to use. The selector is using the Kirby core functions to create the thumbnail. You could either:
- allow PHP to use more memory or
- try switch from GD to Imagemagic or vise versa in you sites config file: http://getkirby.com/docs/cheatsheet/options/thumbs-driver
