### ISSUE TITLE
Call to undefined method: panel()->language()

### ISSUE THREAD

**Issue by jensfranke** [storypioneers/kirby-selector#34]
First of all: Thanks for the great plugin!

With the latest files from the dev-branch of kirby I get the following error:

Fatal error: Call to undefined method Kirby\Panel::language() in … site/fields/selector/selector.php on line 148

return 'de' or 'en' manually works fine.

**Comment by ralfgoeke** [comment]
Ran into it yesterday morning, too. But Bastian fixed it on the dev-branch in the meantime, so it's working again. :)

**Comment by JonasDoebertin** [comment]
Should be fixed with the [1.5.1 update](https://github.com/storypioneers/kirby-selector/releases/tag/1.5.1) I just released.
