### ISSUE TITLE
"Notice: Array to string conversion" when value is not setted

### ISSUE THREAD

**Issue by sudomf** [storypioneers/kirby-selector#4]
I had a "Notice: Array to string conversion" when I used the plugin for the first time, I had find a simple solution changing the template.php:

`<input class="[ js-selector-storage ]" type="hidden" name="<?= $field->name() ?>" id="<?= $field->name() ?>" value="<?= $field->value() ?>" />`

for

`<input class="[ js-selector-storage ]" type="hidden" name="<?= $field->name() ?>" id="<?= $field->name() ?>" value="<?php if(!empty($field->value())) echo implode(",",$field->value())  ?>" />`

;)

**Comment by JonasDoebertin** [comment]
Hi @mayke5421,

thanks for letting me know! I just released an update (1.0.2) that should fix this issue.

**Comment by sudomf** [comment]
Ok, It is a awesome plugin ;)
