### ISSUE TITLE
[Feature Request] Please Be Compatible with The Official Kirby CLI 

### ISSUE THREAD

**Issue by luxlogica** [storypioneers/kirby-selector#41]
Please provide support for the official **[Kirby CLI](http://github.com/getkirby/cli)**, an amazing tool that allows power users to instal, update and manage kirby sites - and their plugins - through the command-line.

You can view the [official announcement](https://forum.getkirby.com/t/introducing-the-kirby-cli/) by Bastian on the Kirby Forum, [here](https://forum.getkirby.com/t/introducing-the-kirby-cli/).

**Comment by dgdsp** [comment]
should work w/ v1.5.2
