### ISSUE TITLE
Multiple selector fields in blueprint not possible?

### ISSUE THREAD

**Issue by ToGe88** [storypioneers/kirby-selector#46]
Hey there,
it seems, that it is not possible to put multiple selector fields in one blueprint. Every time i do that the second one is not shown at all? Could that be a bug?

Thanks so far.

**Comment by texnixe** [comment]
You can use as many selector fields as you want. The important thing is to give your fields unique names.

**Comment by ToGe88** [comment]
ok now i got it. don't know what the problem was. i'll keep you up... 

thanks so far.
