### ISSUE TITLE
Install plugin via Kirby CLI

### ISSUE THREAD

**Issue by mattlenz** [storypioneers/kirby-selector#47]
It would be nice to be able to install this plugin via the [Kirby CLI](https://github.com/getkirby/cli).

A `package.json` file will need to be added to this project with `"type": "kirby-field"` set.

The install command would then be

``` sh
kirby plugin:install storypioneers/kirby-selector
```

**Comment by mattlenz** [comment]
Added PR #48.

**Comment by dgdsp** [comment]
thanks for the PR!

I hope @JonasDoebertin can add this to the repo asap…

**Comment by dgdsp** [comment]
should work now.
