### ISSUE TITLE
Readme install instructions need clarification

### ISSUE THREAD

**Issue by joshkpeterson** [storypioneers/kirby-selector#53]
I'm new to Kirby so that might be half of it, but I'm having trouble understanding how to get this working.

The install instructions say:

> Copy or link the selector directory to site/plugins/

But there's no directory called 'selector'. I think you just mean to drop the entire contents of the repo in a directory inside site/plugins ? When I install with kirby-cli, it does this into a site/plugins/field-selector.

Then in the blueprints instructions, it goes on to say:

> As soon as you dropped the field extension into your fields folder

Do I need to move something into another directory for this to work? Which plugin directory into where?

Thanks!

**Comment by texnixe** [comment]
If you install the plugin via the Kirby Cli, you don't have to move anything anywhere. The plugin needs to go into /site/plugins.

> As soon as you dropped the field extension into your fields folder

This line is a leftover of the former instructions, before the field was turned into a plugin, so you can ignore this.

**Comment by dgdsp** [comment]
should be fixed now , thank you @texnixe for helping out!
