### ISSUE TITLE
Kirby CLI and plugin support #48 #49 breaks submodule support

### ISSUE THREAD

**Issue by DenisLanz** [storypioneers/kirby-selector#54]
1b4d8cc0 breaks the field in my case when it is added as submodule needed to revert to da82bc66 it doesn't get loaded anymore by kirby.

**Comment by Thiousi** [comment]
Did you add it as a submodule in the plugins folder or in the fields folder?

**Comment by DenisLanz** [comment]
In the fields folder, its a field, right?

**Comment by Thiousi** [comment]
It's actually now packaged as a plug-in. Which is why it wasn't working for
you. If you put it in the plug-ins folder, as stated in the docs, it will
register the field.

**Comment by DenisLanz** [comment]
Ah, good to know. I routinely update my submodules without looking at the docs of each plugin each time ;)
