### ISSUE TITLE
The selector field is missing. 

### ISSUE THREAD

**Issue by raphaelokon** [storypioneers/kirby-selector#58]
Hi there.

I moved the plugin from `/site/fields` to `/site/plugins` … now I m getting the following error message:

```
The selector field is missing. Please add it to your installed fields or remove it from your blueprint
```

**Comment by texnixe** [comment]
Have you made sure that the folder has the same name as the plugin file?

**Comment by raphaelokon** [comment]
Blimey … it was named `selector` instead `field-selector`. Thanks.

**Comment by rutger1140** [comment]
I had the same issue. Perhaps the `field-selector.php` [file](https://github.com/storypioneers/kirby-selector/blob/master/field-selector.php) should be renamed to `selector.php` to prevent mistakes? 
Or am I missing something...

**Comment by SirNovi** [comment]
The readme clearly states to put the `selector` folder into `site/plugins` but like that it's not working. Reading the note from raphaelokon I tried renaming it field-selector which seems to fix it. This is not mentioned in the readme, the folder name and readme should be changed accordingly.
