### ISSUE TITLE
Issue using `single` mode

### ISSUE THREAD

**Issue by bovisp** [storypioneers/kirby-selector#6]
When I am using your selector in `single` mode. There is an issue when I drag and drop an image from the Files section to your Main Image form field. When I do this, any unsaved changes that I have made to the other fields dissappear.

Oh yeah. I love this by the way! Great job!

**Comment by JonasDoebertin** [comment]
I'm unable to reproduce that.

When I drag a file from the panels "Files" section onto a "selector" field, exactly nothing happens. No page reload, no loss of unsaved content changes, nothing.

**Comment by bovisp** [comment]
`@JonasDoebertin` I will send you an animated GIF later today so you can see the issue I'm having. This could just be unique to me.

**Comment by bovisp** [comment]
`@JonasDoebertin` if nobody else comments on this issue within a day or two, I will have no problems closing this issue, but I would like to try you're plugin on a fresh install of kirby. If it works there, I will re-add the rest of my code bit by bit and see if your plug-in breaks for me again. If it does break, I'll send you the full documentation of what I did for future reference.

**Comment by JonasDoebertin** [comment]
@bovisp I still don't know how this issue happens. Do you mind providing more info?

**Comment by bovisp** [comment]
Hi @JonasDoebertin . I have been incredibly busy with work and family and have not had time to sit down and take care of this issue. I am going to close it for now. When I have a moment to look at it with a fresh install of kirby and the issue still occurs, I will et you know.
