### ISSUE TITLE
Files sorting not working

### ISSUE THREAD

**Issue by MathiasGmeiner** [storypioneers/kirby-selector#8]
Currently it's not possible to get the files in the multiple field mode in the same order as in the page object.

This is the code to get that behaviour (selector.php on line 177):

``` php
return $this->page()->files()->sortBy('sort', 'asc')->filter(function($file) use ($field) {
 return $field->includeAllFiles() or in_array($file->type(), $field->types);
});
```

**Comment by JonasDoebertin** [comment]
@suedsuedobst I just implemented an in-depth sorting option. You can check it out at the `develop` branch for now.

**Comment by MathiasGmeiner** [comment]
@JonasDoebertin Looks great, thanks a lot!
